Capstone Project
MarwanDev/Tengo-Wallet pull request #1
Opened 2023-08-10 16:14 UTC by MarwanDev

# Capstone Project
## In this project I did the following:

#### Interactions
- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
    - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

#### Testing requirements
- Create unit and integration tests for all the most important components of your RoR application.

2023-08-10 17:22 UTC, elisha2kyakpo1 requested changes
Hi 👋 @MarwanDev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ The PR title and description are good and professional.
✔️ No linter errors.
✔️ Descriptive readme file.
✔️ Tests passing👏

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 17:22 UTC, elisha2kyakpo1 commented on README.md
> +
- [ ] Kindly fix the error with the deployed link after sign up. I am sure it is something to do with email confirmation. Since email confirmation is not a requirement, you can remove this functionality.


![live](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/a8589554-fcf1-4221-ba66-1fed99e42d71)

2023-08-10 17:22 UTC, elisha2kyakpo1 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Great job recording a video, but you did not meet all the video requirements, you did not present a piece of code you are proud of.

![video](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/039467cc-2da7-487c-9718-390ca072ecf6)

2023-08-10 17:22 UTC, elisha2kyakpo1 commented on README.md
> +
- [ ] Kindly show acknowledgments for the designs in the readme file.


![readme](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/81fbf4c4-607d-456e-8090-ad84538a8154)

2023-08-10 17:22 UTC, elisha2kyakpo1 commented on app/views/transaction_categories/_form.html.erb
> +  </div>
- [ ] Kindly add a selection functionality on the transaction form, users should be able to choose a category they want to add a transaction to.

![trasact](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/2ec428d4-7f4e-4db9-bd24-cb8777e3f792)


![form](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/55abc154-3b32-4e40-8d34-23849f4402fc)

2023-08-10 17:22 UTC, elisha2kyakpo1 commented on spec/features/categories_show_spec.rb
> +    end
- [ ] Kindly add more test files and test models and other controllers.
- [ ] Kindly fix the tests which are not passing.

![test](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/8768d4be-9285-4318-ad7c-b19f6493b9e2)



![tests](https://github.com/MarwanDev/Tengo-Wallet/assets/53124548/e9c15469-02b4-4e29-b30f-e3122c9d8b2b)

2023-08-11 13:18 UTC, MarwanDev commented
Kindly check the screenshot below as it shows how all tests passed
![Capturenow](https://github.com/MarwanDev/Tengo-Wallet/assets/46492634/8f8bef90-b146-4ea3-8f3d-fedab4c11dc8)

2023-08-11 13:57 UTC, Reem-lab approved these changes
# Hi @MarwanDev, 👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ] Great working on the styles ✨🎉
- [ ] Followed Gitflow 🙏🏻
- [ ] Professional README ✨
- [ ] Descriptive PR 💯💯
- [ ] No Linters error ✅
- [ ] Good working on the functionality  🔥
- [ ] Deployed well 🤩🚀
- [ ] Great working on the tests, All passed ✅✅
- [ ] Great working on the video presentation and mentioning the part you are proud ⭐


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 13:57 UTC, Reem-lab commented on README.md
> +I would like to thank the Microverse community and The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) for such a great design
- [ OPTIONAL ] Great job for adding the acknowledgment but I think you linked it to the wrong link so please link it to the Original design idea by [Gregoire Vella on Behance](https://www.behance.net/gregoirevella). ⭐🤩 so kindly add it 💯

![image](https://github.com/MarwanDev/Tengo-Wallet/assets/58553711/c30fc708-0c7d-49d0-a593-6f42c622e19d)

2023-08-11 14:00 UTC, merged